LFS now uses Eudev, a fork of systemd's udev by Gentoo. This commit brings GoboALFS up-to-date with LFS.

diff --git a/GoboALFS b/GoboALFS
--- a/GoboALFS
+++ b/GoboALFS
@@ -115,7 +115,7 @@ then
     popd > /dev/null
 fi
 
-if [ ! -d "$BUILDDIR/Programs/BootScripts-ALFS" ]
+if [ ! -d "$BUILDDIR/Programs/BootScripts-ALFS" -o ! -d "$BUILDDIR/Programs/LibXML2" ]
 then
     pushd "$WORKDIR/jhalfs-trunk" > /dev/null
     echo "Running menuconfig."
@@ -132,7 +132,7 @@ fi
 # Move left-over files to the packages where they belong
 
 MoveSettingsFile nsswitch.conf Glibc
-MoveSettingsFile udev/hwdb.bin Udev
+MoveSettingsFile udev/hwdb.bin Eudev
 MoveSettingsFile inittab BootScripts-ALFS
 MoveSettingsFile syslog.conf Sysklogd
 
@@ -179,18 +179,18 @@ then
     echo nameserver 208.67.222.222 | sudo tee -a "$BUILDDIR/System/Settings/resolv.conf" > /dev/null
     echo nameserver 208.67.220.220 | sudo tee -a "$BUILDDIR/System/Settings/resolv.conf" > /dev/null
 fi
-sudoers_file="$BUILDDIR/Programs/Sudo/Current/Resources/Defaults/Settings/sudoers"
-if sudo grep -q "^root" "$sudoers_file"
+eudevVersion=$(ls "$BUILDDIR/Programs/Eudev/" 2> /dev/null | grep -v "Settings\|Current")
+if [ -z "$eudevVersion" ]
 then
-    sudo perl -pi -e "s/^root/gobo/g" "$sudoers_file"
+    echo "ERROR: Eudev has not been found at $BUILDDIR/Programs/Eudev/"
+    exit 1
 fi
-udevVersion=$(ls "$BUILDDIR/Programs/Udev/" | grep -v "Settings\|Current")
-for rulefile in "$BUILDDIR/Programs/Udev/$udevVersion/Resources/Defaults/Settings/udev/rules.d"/*
+for rulefile in "$BUILDDIR/Programs/Eudev/$eudevVersion/Resources/Defaults/Settings/udev/rules.d"/*
 do
     grep -q "pci-db" "$rulefile" && sudo perl -pi -e "s,pci-db,hwdb --subsystem=pci,g" "$rulefile"
     grep -q "usb-db" "$rulefile" && sudo perl -pi -e "s,usb-db,hwdb --subsystem=usb,g" "$rulefile"
 done
-sudo rm -f "$BUILDDIR/Programs/Udev/$udevVersion/Resources/Defaults/Settings/udev/rules.d/55-lfs.rules"
+sudo rm -f "$BUILDDIR/Programs/Eudev/$eudevVersion/Resources/Defaults/Settings/udev/rules.d/55-lfs.rules"
 
 # Make sure we have /bin/sh
 
